// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/prayer_model.dart';
import 'models/streak_model.dart';
import 'models/user_profile_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1338698365441690232),
    name: 'Prayer',
    lastPropertyId: const obx_int.IdUid(4, 4985978825233514570),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1781763481287396281),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6676940911030062734),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3906021497468251084),
        name: 'isCompleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4985978825233514570),
        name: 'date',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 706345959104340872),
    name: 'Streak',
    lastPropertyId: const obx_int.IdUid(10, 6392053059665417157),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 86702272585025853),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8786729964557317049),
        name: 'count',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4987530681952276612),
        name: 'goal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7916892743323186033),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 85010084430651590),
        name: 'emotion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4931378688834158035),
        name: 'moodIntensity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1720440084525908862),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2608692504366397466),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6392053059665417157),
        name: 'isSuccess',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8512291693082550534),
    name: 'UserProfile',
    lastPropertyId: const obx_int.IdUid(11, 2007209796577511304),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7626070384926860621),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4919641217540815294),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 671748751485565877),
        name: 'goals',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7411803757707392293),
        name: 'hobbies',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6796478754985101917),
        name: 'triggers',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3751846143681267266),
        name: 'streakGoal',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7587397390803279660),
        name: 'passwordHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1708789767381654030),
        name: 'biometricEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3497005368154987552),
        name: 'notificationsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7007787891191731417),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2007209796577511304),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8512291693082550534),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [6437257444821216180],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Prayer: obx_int.EntityDefinition<Prayer>(
      model: _entities[0],
      toOneRelations: (Prayer object) => [],
      toManyRelations: (Prayer object) => {},
      getId: (Prayer object) => object.id,
      setId: (Prayer object, int id) {
        object.id = id;
      },
      objectToFB: (Prayer object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addBool(2, object.isCompleted);
        fbb.addInt64(3, object.date.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isCompletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = Prayer(
          id: idParam,
          name: nameParam,
          isCompleted: isCompletedParam,
          date: dateParam,
        );

        return object;
      },
    ),
    Streak: obx_int.EntityDefinition<Streak>(
      model: _entities[1],
      toOneRelations: (Streak object) => [],
      toManyRelations: (Streak object) => {},
      getId: (Streak object) => object.id,
      setId: (Streak object, int id) {
        object.id = id;
      },
      objectToFB: (Streak object, fb.Builder fbb) {
        final emotionOffset = fbb.writeString(object.emotion);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.count);
        fbb.addInt64(2, object.goal);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addOffset(5, emotionOffset);
        fbb.addInt64(6, object.moodIntensity);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.lastUpdated.millisecondsSinceEpoch);
        fbb.addBool(9, object.isSuccess);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final countParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final goalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final emotionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final moodIntensityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isSuccessParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final dateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = Streak(
          id: idParam,
          count: countParam,
          goal: goalParam,
          emotion: emotionParam,
          moodIntensity: moodIntensityParam,
          isSuccess: isSuccessParam,
          date: dateParam,
          createdAt: createdAtParam,
          lastUpdated: lastUpdatedParam,
        );

        return object;
      },
    ),
    UserProfile: obx_int.EntityDefinition<UserProfile>(
      model: _entities[2],
      toOneRelations: (UserProfile object) => [],
      toManyRelations: (UserProfile object) => {},
      getId: (UserProfile object) => object.id,
      setId: (UserProfile object, int id) {
        object.id = id;
      },
      objectToFB: (UserProfile object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final goalsOffset = fbb.writeList(
          object.goals.map(fbb.writeString).toList(growable: false),
        );
        final hobbiesOffset = fbb.writeList(
          object.hobbies.map(fbb.writeString).toList(growable: false),
        );
        final triggersOffset = fbb.writeList(
          object.triggers.map(fbb.writeString).toList(growable: false),
        );
        final passwordHashOffset = fbb.writeString(object.passwordHash);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, goalsOffset);
        fbb.addOffset(3, hobbiesOffset);
        fbb.addOffset(4, triggersOffset);
        fbb.addInt64(5, object.streakGoal);
        fbb.addOffset(6, passwordHashOffset);
        fbb.addBool(7, object.biometricEnabled);
        fbb.addBool(8, object.notificationsEnabled);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final goalsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final hobbiesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final triggersParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final streakGoalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final passwordHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final biometricEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final notificationsEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
        );
        final object = UserProfile(
          id: idParam,
          name: nameParam,
          goals: goalsParam,
          hobbies: hobbiesParam,
          triggers: triggersParam,
          streakGoal: streakGoalParam,
          passwordHash: passwordHashParam,
          biometricEnabled: biometricEnabledParam,
          notificationsEnabled: notificationsEnabledParam,
          createdAt: createdAtParam,
          lastUpdated: lastUpdatedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Prayer] entity fields to define ObjectBox queries.
class Prayer_ {
  /// See [Prayer.id].
  static final id = obx.QueryIntegerProperty<Prayer>(
    _entities[0].properties[0],
  );

  /// See [Prayer.name].
  static final name = obx.QueryStringProperty<Prayer>(
    _entities[0].properties[1],
  );

  /// See [Prayer.isCompleted].
  static final isCompleted = obx.QueryBooleanProperty<Prayer>(
    _entities[0].properties[2],
  );

  /// See [Prayer.date].
  static final date = obx.QueryDateProperty<Prayer>(_entities[0].properties[3]);
}

/// [Streak] entity fields to define ObjectBox queries.
class Streak_ {
  /// See [Streak.id].
  static final id = obx.QueryIntegerProperty<Streak>(
    _entities[1].properties[0],
  );

  /// See [Streak.count].
  static final count = obx.QueryIntegerProperty<Streak>(
    _entities[1].properties[1],
  );

  /// See [Streak.goal].
  static final goal = obx.QueryIntegerProperty<Streak>(
    _entities[1].properties[2],
  );

  /// See [Streak.date].
  static final date = obx.QueryDateProperty<Streak>(_entities[1].properties[3]);

  /// See [Streak.emotion].
  static final emotion = obx.QueryStringProperty<Streak>(
    _entities[1].properties[4],
  );

  /// See [Streak.moodIntensity].
  static final moodIntensity = obx.QueryIntegerProperty<Streak>(
    _entities[1].properties[5],
  );

  /// See [Streak.createdAt].
  static final createdAt = obx.QueryDateProperty<Streak>(
    _entities[1].properties[6],
  );

  /// See [Streak.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<Streak>(
    _entities[1].properties[7],
  );

  /// See [Streak.isSuccess].
  static final isSuccess = obx.QueryBooleanProperty<Streak>(
    _entities[1].properties[8],
  );
}

/// [UserProfile] entity fields to define ObjectBox queries.
class UserProfile_ {
  /// See [UserProfile.id].
  static final id = obx.QueryIntegerProperty<UserProfile>(
    _entities[2].properties[0],
  );

  /// See [UserProfile.name].
  static final name = obx.QueryStringProperty<UserProfile>(
    _entities[2].properties[1],
  );

  /// See [UserProfile.goals].
  static final goals = obx.QueryStringVectorProperty<UserProfile>(
    _entities[2].properties[2],
  );

  /// See [UserProfile.hobbies].
  static final hobbies = obx.QueryStringVectorProperty<UserProfile>(
    _entities[2].properties[3],
  );

  /// See [UserProfile.triggers].
  static final triggers = obx.QueryStringVectorProperty<UserProfile>(
    _entities[2].properties[4],
  );

  /// See [UserProfile.streakGoal].
  static final streakGoal = obx.QueryIntegerProperty<UserProfile>(
    _entities[2].properties[5],
  );

  /// See [UserProfile.passwordHash].
  static final passwordHash = obx.QueryStringProperty<UserProfile>(
    _entities[2].properties[6],
  );

  /// See [UserProfile.biometricEnabled].
  static final biometricEnabled = obx.QueryBooleanProperty<UserProfile>(
    _entities[2].properties[7],
  );

  /// See [UserProfile.notificationsEnabled].
  static final notificationsEnabled = obx.QueryBooleanProperty<UserProfile>(
    _entities[2].properties[8],
  );

  /// See [UserProfile.createdAt].
  static final createdAt = obx.QueryDateProperty<UserProfile>(
    _entities[2].properties[9],
  );

  /// See [UserProfile.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<UserProfile>(
    _entities[2].properties[10],
  );
}
